@CoreNotify.API_HostAddress = https://localhost:7080

POST {{CoreNotify.API_HostAddress}}/api/account/register
Accept: application/json
Content-Type: application/json

{
  "email": "adamfoneil@proton.me",
  "domainName": "sqlchartify.io"
}

###
