version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: Hello.1234!
      POSTGRES_DB: devdb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
