name: Build and Push to GHCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./publish

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        cd publish
        echo "FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base" > Dockerfile
        echo "WORKDIR /app" >> Dockerfile
        echo "COPY . ." >> Dockerfile
        echo "ENTRYPOINT [\"dotnet\", \"YourApp.dll\"]" >> Dockerfile
        docker build -t ghcr.io/${{ github.repository_owner }}/core-notify:latest .
        docker push ghcr.io/${{ github.repository_owner }}/core-notify:latest
